# Generated by Django 4.1.5 on 2023-02-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionCursos', '0002_alter_alumnos_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='tfno',
            field=models.CharField(max_length=9, verbose_name='teléfono'),
        ),
    ]
